import type { MetadataRoute } from "next";
import {
  BRAND_BACKGROUND_COLOR,
  BRAND_THEME_COLOR,
  SITE_DESCRIPTION,
  SITE_NAME,
} from "@/lib/metadata/site";

// Web app manifest — Issue #171
//
// Served at /manifest.webmanifest and linked automatically by Next.js.
// Icon URLs point at the sizes generated by src/app/icon.tsx.

export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: SITE_NAME,
    short_name: SITE_NAME,
    description: SITE_DESCRIPTION,
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: BRAND_BACKGROUND_COLOR,
    theme_color: BRAND_THEME_COLOR,
    categories: ["finance", "entertainment", "shopping"],
    icons: [
      { src: "/icon/192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon/512", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/favicon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    ],
  };
}
